Update versions of actions/download-artifact and actions/upload-artifact
SofaDefrost/Shell pull request #5
Opened 2024-09-12 14:07 UTC by antennae

https://github.com/sofa-framework/sofa/discussions/4979

2024-09-13 09:05 UTC, epernod commented
You don't need to also update the download-artifact@v2 ?

2024-09-13 09:08 UTC, alxbilger requested changes
actions/download-artifact@v2 must be updated

2024-09-13 10:29 UTC, epernod approved these changes

2024-09-16 07:49 UTC, bakpaul approved these changes

2024-11-19 07:56 UTC, merged